import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../../components/theme-provider";
import AuthProvider from "../../context/AuthProvider";
const inter = Inter({ subsets: ["latin"] });
import MainHeader from "../../components/shared/Header";
import Footer from "../../components/shared/Footer";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainHeader />
        {/* <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          > */}
        <AuthProvider>
          {children}
        </AuthProvider>
        {/* </ThemeProvider> */}
        <Footer
          name="Vishal Sharma"
          email="sharmavs9205@gmail.com"
          phone="+91 7303876390"
        />
      </body>
    </html>
  );
}
